const MODAL_TYPE = Object.freeze({
    CREATE_STRATEGY: 'CREATE_STRATEGY',
    DEFAULT: '',
    CONNECT_MT5: 'CONNECT_MT5',
    CAPITAL_ALLOCATION: 'CAPITAL_ALLOCATION',
    CONFIG_MODAL: 'CONFIG_MODAL'
})

export default MODAL_TYPE
